Develop
wezelbul/java-filmorate pull request #23
Opened 2022-10-12 11:11 UTC by wezelbul

Привет!
У нас весь базовый функционал согласно канбан-доски, за исключением рефакторинга и презентации

2022-10-12 19:13 UTC, eugene-lenkevich requested changes
Привет, Дмитрий , спасибо за PR

В целом все сделанно аккуратно, очень приятно проверять работы :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-10-12 19:13 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/DbEventStorage.java
> +    private static final String SELECT_BY_USER_ID_SQL_QUERY = UtilReader.readString(SQL_QUERY_DIR + "select_by_user_id.sql");
Вот этот код повторяется

` UtilReader.readString(SQL_QUERY_DIR `

Мне кажется что эту логику получения текста запроса не стоит дублировать, как то оформить иди в метод или в конструкторе в цикле послеовательно переменные инициализировать, как именно - надо подумать, есть несколько вариантов :)
Можно например enum создать
@RequiredArgsConstructor
enum Requests {
SELECT_BY_USER_ID_SQL_QUERY ("select_by_user_id.sql")
...
private final String fileName;
}

ну или прост метод 

SELECT_BY_USER_ID_SQL_QUERY  = UtilReader.loadRequest("select_by_user_id.sql")

главное побольше спрятать деталей реализации

2022-10-12 19:13 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/friend/DbFriendStorage.java
> +            return userFriends.query(SELECT_ALL_SQL_QUERY, new UserMapper(), userId);
На каждый запрос будет создаваться новый объект
`new UserMapper()`
может создать его один раз и потом испольовать во всех запросах? :)

2022-10-12 19:13 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/DbLikeStorage.java
> +        return filmLikes.query(SELECT_COUNT_LIMIT_GENRE_SQL_QUERY, new FilmExtractor(), count, genreId);
new FilmExtractor()

Вот опять таки, чем больше мелких короткоживущих объектов создается, тем больше нагрузкана сборщик мусора. Тут, и во многих других местах, можно не пересоздавать подбные объекты, а использовать уже созданные :)

2022-10-12 22:42 UTC, wezelbul commented on src/main/java/ru/yandex/practicum/filmorate/exception/search/SearchEmptyRequestParamException.java
> +public class SearchEmptyRequestParamException extends RuntimeException {
Нет исключения - нет проблемы :D

2022-10-12 23:25 UTC, wezelbul commented on src/main/java/ru/yandex/practicum/filmorate/storage/event/DbEventStorage.java
> +    private static final String SELECT_BY_USER_ID_SQL_QUERY = UtilReader.readString(SQL_QUERY_DIR + "select_by_user_id.sql");
Мысль об enum - моё почтение, мне понравилось

2022-10-13 08:07 UTC, eugene-lenkevich requested changes
Ага, спасибо за доработку. 
Интересно получилось с енамами, единственное,  для чистоты совести, давай еще немного поправим и не будем их каждый раз читать при обращении :)

2022-10-13 08:39 UTC, wezelbul commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorRequests.java
> +        return UtilReader.readString(SQL_QUERY_DIR + this.fileName);
да, я в какой-то момент понял, что опять вернулся к многократным чтениям, а потом отвлёкся и не вспомнил уже

2022-10-14 07:03 UTC, eugene-lenkevich approved these changes

2022-11-10 12:13 UTC, merged